FROM postgres:15.3-alpine3.18

COPY init.sql /docker-entrypoint-initdb.d/

ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD 0constans
ENV POSTGRES_DB bike_renting_system

RUN chmod +r /docker-entrypoint-initdb.d/init.sql